version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - texlive-xetex
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - latexmk
    - fonts-fandol
    - inkscape
    - ghostscript
    
# Build from the docs/ directory with Sphinx
sphinx:
  configuration: conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: requirements.txt
    
formats: all
